# Generated by Django 2.1.5 on 2019-02-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuron', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
